INSERT INTO CriterionGroup(name)
VALUES ('GENERAL'),
       ('CREATE_COLLECTION'),
       ('INSERT'),
       ('UPDATE'),
       ('FIND'),
       ('AGGREGATE');

INSERT INTO Criterion(name, description, min_score, group_id, priority)
VALUES ('CREATE_ONE_COLLECTION', 'Explicitly create one or two collections', 1, 2, 1),
       ('INSERT_TEN_DOCUMENTS', 'Insert 10 documents into each collection. These documents must be non-trivial', 10, 3,
        2),
       ('INSERT_DOCUMENT_EMBEDDED', 'Insert at least one document with an embedded object', 1, 3, 3),
       ('INSERT_DOCUMENT_ARRAY', 'Insert at least one document with an array', 1, 3, 4),
       ('INSERT_ONE_USED', 'Use insertOne operator', 1, 3, 5),
       ('INSERT_MANY_USED', 'Use insertMany operator', 1, 3, 6),
       ('REPLACE_VALUE', 'Replace the value of the document', 1, 4, 7),
       ('UPDATE_ONE_DOCUMENT', 'Update an individual field of one document', 1, 4, 8),
       ('UPDATE_MANY_FORMULA',
        'Update an individual field in many documents by criterion; use a formula or increase/multiply the value', 1, 4,
        9),
       ('UPDATE_ADD_FIELD', 'Add a field in the document(s)', 1, 4, 10),
       ('UPDATE_REMOVE_FIELD', 'Remove a field in the document(s)', 1, 4, 11),
       ('UPDATE_NESTED_DOCUMENT', 'Modify a nested document', 1, 4, 12),
       ('UPDATE_ARRAY', 'Modify an array', 1, 4, 13),
       ('UPSERT_USED', 'Use the upsert mode at least once', 1, 4, 14),
       ('FIND_FIVE',
        'Express at least 5 find queries (with non-trivial selections, i.e. the first parameter cannot be empty)', 5, 5,
        15),
       ('FIND_LOGICAL_OPERATOR', 'Use at least one logical operator ($and, $or, $not)', 1, 5, 16),
       ('FIND_COMPARISON', 'Use greater than or less than, etc.', 1, 5, 17),
       ('FIND_ARRAY_OPERATOR', 'Use operation with array fields at least once', 1, 5, 18),
       ('FIND_DATE_OPERATOR',
        'Use operation with dates or parts of dates (for example, select all orders for a given date or all orders for a given year)',
        1, 5, 19),
       ('POSITIVE_PROJECTION', 'Use positive projection (at least once)', 1, 5, 20),
       ('NEGATIVE_PROJECTION', 'Use negative projection (at least once)', 1, 5, 21),
       ('SORT_MODIFIER', 'Use sort modifier at least once', 1, 5, 22),
       ('AGGREGATE_FIVE',
        'Express 5 aggregate operations. Use 2 created collections for entities of different types. If necessary, insert more documents into each one of them',
        5, 6, 23),
       ('STAGE_MATCH', 'Use at least once $match stage', 1, 6, 24),
       ('STAGE_GROUP', 'Use at least once $group stage', 1, 6, 25),
       ('STAGE_SORT', 'Use at least once $sort stage', 1, 6, 26),
       ('STAGE_PROJECT_ADDFIELDS', 'Use at least once $project (or $addFields) stage', 1, 6, 27),
       ('AGGREGATOR_SUM_AVG', 'Use at least once $sum (or $avg)', 1, 6, 28),
       ('AGGREGATOR_COUNT', 'Use at least once $count', 1, 6, 29),
       ('AGGREGATOR_MIN_MAX', 'Use at least once $min (or $max)', 1, 6, 30),
       ('LOOKUP', 'Use lookup (if you have two collections)', 1, 6, 31),
       ('COMMENT', 'Describe the real-world meaning of all your queries in comments', 1, 1, 32);
